### PR TITLE
Publication model changes

### PR DESCRIPTION
**Pull request by mariahvadak**

### CODE REVIEW

**Comment by jonathanmiller2** [comment]
Have you deleted the /publications/ directory? If not, you should.

**Comment by mariahvadak** [comment]
> Have you deleted the /publications/ directory? If not, you should
> 
> Our goal is to remove it entirely

It should be moved now

**Comment by jonathanmiller2** [comment]
That's better
I notice you made a directory that's /templates/aboutus/publications/
This should just be /templates/aboutus/ and then contain all the publications files
Having more folders might be more organized in the long run, but presently that format doesn't match the other apps

**Comment by mariahvadak** [comment]
> That's better I notice you made a directory that's /templates/aboutus/publications/ This should just be /templates/aboutus/ and then contain all the publications files Having more folders might be more organized in the long run, but presently that format doesn't match the other apps

Ok, I took those files out and deleted that publications folder

**Comment by jonathanmiller2** [comment]
Check the indentation of app/ceom/aboutus/urls.py. If it looks uniform on VSCode you can click and drag over the indent part and VSCode will tell you if there's a difference

Screenshot 2022-12-15 170051

Remove the empty "detail" view from app/ceom/aboutus/views.py

Remove the comments from lines 136-144 or beyond in app/ceom/aboutus/models.py

Good job on merging imports on line 5 in app/ceom/aboutus/views.py, you did it correctly
And good job figuring out that you needed to change app/ceom/settings.py to remove the publications app

**Comment by mariahvadak** [comment]
> Check the indentation of app/ceom/aboutus/urls.py. If it looks uniform on VSCode you can click and drag over the indent part and VSCode will tell you if there's a difference
> 
> Screenshot 2022-12-15 170051
> 
> Remove the empty "detail" view from app/ceom/aboutus/views.py
> 
> Remove the comments from lines 136-144 or beyond in app/ceom/aboutus/models.py
> 
> Good job on merging imports on line 5 in app/ceom/aboutus/views.py, you did it correctly And good job figuring out that you needed to change app/ceom/settings.py to remove the publications app

I removed the extra stuff and went ahead and fixed the education url
I also checked the indentation with the screenshot you sent and it should be fixed now

**Pull request merged**
